name = "claude4free-api"
main = "worker.js"
compatibility_date = "2024-01-15"

[env.production]
name = "claude4free-api"
workers_dev = false
[env.production.vars]
ENVIRONMENT = "production"

[env.development]
name = "claude4free-api-dev"
workers_dev = true
[env.development.vars]
ENVIRONMENT = "development" 